// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceHub.Infrastructure.Contexts;

#nullable disable

namespace ResourceHub.Infrastructure.Migrations
{
    [DbContext(typeof(ResourceHubDbContext))]
    [Migration("20260729120925_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ResourceHub.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActivityNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChangedOn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DeletionInd")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LongTxt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryLang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceCat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortTxt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValuationClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
