// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceHub.Infrastructure.Contexts;

#nullable disable

namespace ResourceHub.Infrastructure.Migrations
{
    [DbContext(typeof(ResourceHubDbContext))]
    partial class ResourceHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ResourceHub.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("activity_no");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("changed_by");

                    b.Property<string>("ChangedOn")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("changed_on");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_on");

                    b.Property<bool>("DeletionInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deletion_ind");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("division");

                    b.Property<string>("LongTxt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("long_txt");

                    b.Property<string>("MaterialGroup")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("material_group");

                    b.Property<string>("PrimaryLang")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("primary_lang");

                    b.Property<string>("ServiceCat")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("service_cat");

                    b.Property<string>("ShortTxt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("short_txt");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<string>("ValuationClass")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("valuation_class");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("ActivityNo")
                        .IsUnique()
                        .HasDatabaseName("ix_services_activity_no");

                    b.ToTable("services", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
